//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tb_confrontation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub line_one_id: i32,
    pub line_two_id: i32,
    pub date_of_confrontation: Date,
    pub point_of_line_one: i16,
    pub point_of_line_two: i16,
    pub group_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_group::Entity",
        from = "Column::GroupId",
        to = "super::tb_group::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbGroup,
    #[sea_orm(
        belongs_to = "super::tb_line::Entity",
        from = "Column::LineOneId",
        to = "super::tb_line::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbLine2,
    #[sea_orm(
        belongs_to = "super::tb_line::Entity",
        from = "Column::LineTwoId",
        to = "super::tb_line::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbLine1,
}

impl Related<super::tb_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
