//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tb_group_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub group_id: i32,
    pub role_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_group::Entity",
        from = "Column::GroupId",
        to = "super::tb_group::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbGroup,
    #[sea_orm(
        belongs_to = "super::tb_role::Entity",
        from = "Column::RoleId",
        to = "super::tb_role::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbRole,
    #[sea_orm(
        belongs_to = "super::tb_user::Entity",
        from = "Column::UserId",
        to = "super::tb_user::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbUser,
}

impl Related<super::tb_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbGroup.def()
    }
}

impl Related<super::tb_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbRole.def()
    }
}

impl Related<super::tb_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
