//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tb_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tb_confrontation::Entity")]
    TbConfrontation,
    #[sea_orm(has_many = "super::tb_line::Entity")]
    TbLine,
    #[sea_orm(has_many = "super::tb_player::Entity")]
    TbPlayer,
    #[sea_orm(has_many = "super::tb_user::Entity")]
    TbUser,
}

impl Related<super::tb_confrontation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbConfrontation.def()
    }
}

impl Related<super::tb_line::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbLine.def()
    }
}

impl Related<super::tb_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbPlayer.def()
    }
}

impl Related<super::tb_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
