//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tb_line_player")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub line_id: i32,
    pub player_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_line::Entity",
        from = "Column::LineId",
        to = "super::tb_line::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbLine,
    #[sea_orm(
        belongs_to = "super::tb_player::Entity",
        from = "Column::PlayerId",
        to = "super::tb_player::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbPlayer,
}

impl Related<super::tb_line::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbLine.def()
    }
}

impl Related<super::tb_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbPlayer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
