//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tb_role_permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub role_id: i32,
    pub permission_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_permissions::Entity",
        from = "Column::PermissionId",
        to = "super::tb_permissions::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbPermissions,
    #[sea_orm(
        belongs_to = "super::tb_role::Entity",
        from = "Column::RoleId",
        to = "super::tb_role::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbRole,
}

impl Related<super::tb_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbPermissions.def()
    }
}

impl Related<super::tb_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
