//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tb_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub password: String,
    pub group_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_group::Entity",
        from = "Column::GroupId",
        to = "super::tb_group::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbGroup,
}

impl Related<super::tb_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
