//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tb_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub password: String,
    #[sea_orm(unique)]
    pub email: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tb_group_user::Entity")]
    TbGroupUser,
}

impl Related<super::tb_group_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbGroupUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
